
all: tableau1d tableau2d hollandais holl2f mat33

clean: 
	rm tableau1d tableau2d hollandais holl2f mat33

tableau1d: tableau1d.c
	gcc tableau1d.c -o tableau1d

tableau2d: tableau2d.c
	gcc tableau2d.c -o tableau2d

hollandais: hollandais.c
	gcc hollandais.c -o hollandais

holl2f: holl2f.c
	gcc holl2f.c -o holl2f
	
mat33: mat33.c
	gcc mat33.c -o mat33
	
	
