all: suites chiffres palindrome fiboRecViz hanoi

clean: 
	rm suites chiffres palindrome fiboRecViz hanoi 

suites: suites.c
	gcc suites.c -o suites

chiffres: chiffres.c
	gcc chiffres.c -o chiffres

palindrome: palindrome.c
	gcc palindrome.c -o palindrome
	
fiboRecViz: fiboRecViz.c
	gcc fiboRecViz.c -o fiboRecViz
	
hanoi: hanoi.c
	gcc hanoi.c -o hanoi
