
all: carre duree jour_du_mois lendemain

clean: 
	rm carre duree jour_du_mois lendemain

carre: carre.c
	gcc carre.c -o carre -lm

duree: duree.c
	gcc duree.c -o duree

jour_du_mois: jour_du_mois.c
	gcc jour_du_mois.c -o jour_du_mois

lendemain: lendemain.c
	gcc lendemain.c -o lendemain
