all: pointeurs chaines args tableau_ptr pascal

clean: 
	rm pointeurs chaines args tableau_ptr pascal

pointeurs: pointeurs.c
	gcc pointeurs.c -o pointeurs

chaines: chaines.c
	gcc chaines.c -o chaines

args: args.c
	gcc args.c -o args

tableau_ptr: tableau_ptr.c
	gcc tableau_ptr.c -o tableau_ptr

pascal: pascal.c
	gcc pascal.c -o pascal
	
